// Generated by gencpp from file adding_integers/AddTwoInt.msg
// DO NOT EDIT!


#ifndef ADDING_INTEGERS_MESSAGE_ADDTWOINT_H
#define ADDING_INTEGERS_MESSAGE_ADDTWOINT_H

#include <ros/service_traits.h>


#include <adding_integers/AddTwoIntRequest.h>
#include <adding_integers/AddTwoIntResponse.h>


namespace adding_integers
{

struct AddTwoInt
{

typedef AddTwoIntRequest Request;
typedef AddTwoIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInt
} // namespace adding_integers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::adding_integers::AddTwoInt > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::adding_integers::AddTwoInt&) { return value(); }
};

template<>
struct DataType< ::adding_integers::AddTwoInt > {
  static const char* value()
  {
    return "adding_integers/AddTwoInt";
  }

  static const char* value(const ::adding_integers::AddTwoInt&) { return value(); }
};


// service_traits::MD5Sum< ::adding_integers::AddTwoIntRequest> should match
// service_traits::MD5Sum< ::adding_integers::AddTwoInt >
template<>
struct MD5Sum< ::adding_integers::AddTwoIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::adding_integers::AddTwoInt >::value();
  }
  static const char* value(const ::adding_integers::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::adding_integers::AddTwoIntRequest> should match
// service_traits::DataType< ::adding_integers::AddTwoInt >
template<>
struct DataType< ::adding_integers::AddTwoIntRequest>
{
  static const char* value()
  {
    return DataType< ::adding_integers::AddTwoInt >::value();
  }
  static const char* value(const ::adding_integers::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::adding_integers::AddTwoIntResponse> should match
// service_traits::MD5Sum< ::adding_integers::AddTwoInt >
template<>
struct MD5Sum< ::adding_integers::AddTwoIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::adding_integers::AddTwoInt >::value();
  }
  static const char* value(const ::adding_integers::AddTwoIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::adding_integers::AddTwoIntResponse> should match
// service_traits::DataType< ::adding_integers::AddTwoInt >
template<>
struct DataType< ::adding_integers::AddTwoIntResponse>
{
  static const char* value()
  {
    return DataType< ::adding_integers::AddTwoInt >::value();
  }
  static const char* value(const ::adding_integers::AddTwoIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADDING_INTEGERS_MESSAGE_ADDTWOINT_H
