// Generated by gencpp from file adding_integers/AddTwoIntResponse.msg
// DO NOT EDIT!


#ifndef ADDING_INTEGERS_MESSAGE_ADDTWOINTRESPONSE_H
#define ADDING_INTEGERS_MESSAGE_ADDTWOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adding_integers
{
template <class ContainerAllocator>
struct AddTwoIntResponse_
{
  typedef AddTwoIntResponse_<ContainerAllocator> Type;

  AddTwoIntResponse_()
    : sum(0)  {
    }
  AddTwoIntResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntResponse_

typedef ::adding_integers::AddTwoIntResponse_<std::allocator<void> > AddTwoIntResponse;

typedef boost::shared_ptr< ::adding_integers::AddTwoIntResponse > AddTwoIntResponsePtr;
typedef boost::shared_ptr< ::adding_integers::AddTwoIntResponse const> AddTwoIntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adding_integers::AddTwoIntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adding_integers::AddTwoIntResponse_<ContainerAllocator1> & lhs, const ::adding_integers::AddTwoIntResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adding_integers::AddTwoIntResponse_<ContainerAllocator1> & lhs, const ::adding_integers::AddTwoIntResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adding_integers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::adding_integers::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adding_integers/AddTwoIntResponse";
  }

  static const char* value(const ::adding_integers::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sum\n"
;
  }

  static const char* value(const ::adding_integers::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adding_integers::AddTwoIntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adding_integers::AddTwoIntResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADDING_INTEGERS_MESSAGE_ADDTWOINTRESPONSE_H
