// Generated by gencpp from file adding_integers/AddTwoIntRequest.msg
// DO NOT EDIT!


#ifndef ADDING_INTEGERS_MESSAGE_ADDTWOINTREQUEST_H
#define ADDING_INTEGERS_MESSAGE_ADDTWOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adding_integers
{
template <class ContainerAllocator>
struct AddTwoIntRequest_
{
  typedef AddTwoIntRequest_<ContainerAllocator> Type;

  AddTwoIntRequest_()
    : x(0)
    , y(0)  {
    }
  AddTwoIntRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntRequest_

typedef ::adding_integers::AddTwoIntRequest_<std::allocator<void> > AddTwoIntRequest;

typedef boost::shared_ptr< ::adding_integers::AddTwoIntRequest > AddTwoIntRequestPtr;
typedef boost::shared_ptr< ::adding_integers::AddTwoIntRequest const> AddTwoIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adding_integers::AddTwoIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adding_integers::AddTwoIntRequest_<ContainerAllocator1> & lhs, const ::adding_integers::AddTwoIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adding_integers::AddTwoIntRequest_<ContainerAllocator1> & lhs, const ::adding_integers::AddTwoIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adding_integers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::adding_integers::AddTwoIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adding_integers/AddTwoIntRequest";
  }

  static const char* value(const ::adding_integers::AddTwoIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::adding_integers::AddTwoIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adding_integers::AddTwoIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adding_integers::AddTwoIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADDING_INTEGERS_MESSAGE_ADDTWOINTREQUEST_H
