controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - hip
      - shoulder
      - elbow
      - wrist
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []