// Generated by gencpp from file counting_character/WordCount.msg
// DO NOT EDIT!


#ifndef COUNTING_CHARACTER_MESSAGE_WORDCOUNT_H
#define COUNTING_CHARACTER_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <counting_character/WordCountRequest.h>
#include <counting_character/WordCountResponse.h>


namespace counting_character
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace counting_character


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::counting_character::WordCount > {
  static const char* value()
  {
    return "63b01e3fa790a7c5a731313a78efa4b8";
  }

  static const char* value(const ::counting_character::WordCount&) { return value(); }
};

template<>
struct DataType< ::counting_character::WordCount > {
  static const char* value()
  {
    return "counting_character/WordCount";
  }

  static const char* value(const ::counting_character::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::counting_character::WordCountRequest> should match
// service_traits::MD5Sum< ::counting_character::WordCount >
template<>
struct MD5Sum< ::counting_character::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::counting_character::WordCount >::value();
  }
  static const char* value(const ::counting_character::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::counting_character::WordCountRequest> should match
// service_traits::DataType< ::counting_character::WordCount >
template<>
struct DataType< ::counting_character::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::counting_character::WordCount >::value();
  }
  static const char* value(const ::counting_character::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::counting_character::WordCountResponse> should match
// service_traits::MD5Sum< ::counting_character::WordCount >
template<>
struct MD5Sum< ::counting_character::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::counting_character::WordCount >::value();
  }
  static const char* value(const ::counting_character::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::counting_character::WordCountResponse> should match
// service_traits::DataType< ::counting_character::WordCount >
template<>
struct DataType< ::counting_character::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::counting_character::WordCount >::value();
  }
  static const char* value(const ::counting_character::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COUNTING_CHARACTER_MESSAGE_WORDCOUNT_H
