// Generated by gencpp from file timer_action/TimerAction.msg
// DO NOT EDIT!


#ifndef TIMER_ACTION_MESSAGE_TIMERACTION_H
#define TIMER_ACTION_MESSAGE_TIMERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <timer_action/TimerActionGoal.h>
#include <timer_action/TimerActionResult.h>
#include <timer_action/TimerActionFeedback.h>

namespace timer_action
{
template <class ContainerAllocator>
struct TimerAction_
{
  typedef TimerAction_<ContainerAllocator> Type;

  TimerAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  TimerAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::timer_action::TimerActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::timer_action::TimerActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::timer_action::TimerActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::timer_action::TimerAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::timer_action::TimerAction_<ContainerAllocator> const> ConstPtr;

}; // struct TimerAction_

typedef ::timer_action::TimerAction_<std::allocator<void> > TimerAction;

typedef boost::shared_ptr< ::timer_action::TimerAction > TimerActionPtr;
typedef boost::shared_ptr< ::timer_action::TimerAction const> TimerActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::timer_action::TimerAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::timer_action::TimerAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::timer_action::TimerAction_<ContainerAllocator1> & lhs, const ::timer_action::TimerAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::timer_action::TimerAction_<ContainerAllocator1> & lhs, const ::timer_action::TimerAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace timer_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::timer_action::TimerAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::timer_action::TimerAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timer_action::TimerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timer_action::TimerAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timer_action::TimerAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timer_action::TimerAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::timer_action::TimerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a759c6875ea9b1f22b6751bfc912deb7";
  }

  static const char* value(const ::timer_action::TimerAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa759c6875ea9b1f2ULL;
  static const uint64_t static_value2 = 0x2b6751bfc912deb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::timer_action::TimerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "timer_action/TimerAction";
  }

  static const char* value(const ::timer_action::TimerAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::timer_action::TimerAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"TimerActionGoal action_goal\n"
"TimerActionResult action_result\n"
"TimerActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TimerGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"duration time_to_wait\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TimerResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"duration time_elapsed\n"
"uint32 updates_sent\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"TimerFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: timer_action/TimerFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"duration time_elapsed\n"
"duration time_remaining\n"
;
  }

  static const char* value(const ::timer_action::TimerAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::timer_action::TimerAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimerAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::timer_action::TimerAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::timer_action::TimerAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::timer_action::TimerActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::timer_action::TimerActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::timer_action::TimerActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIMER_ACTION_MESSAGE_TIMERACTION_H
